name: Development Branch Testing

on:
  push:
    branches-ignore: ["main", "next"]
  pull_request:
    branches-ignore: ["main", "next"]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2.5.2
        with:
          node-version: 18
          check-latest: true
          cache: "yarn"

      - name: Install NPM dependencies
        run: yarn install --immutable

      - name: Build app
        run: yarn build

      - name: Run tests with Jest
        run: yarn test:ci

      - uses: cypress-io/github-action@v5
        with:
          install-command: yarn install
          command: yarn dlx cypress run
